### ISSUE TITLE
SoundFile mp3 support across platforms

### ISSUE THREAD

**Issue by kevinstadler** [kevinstadler/processing-sound#2]
From the methCla-based Sound library, users are used to [WAV, AIF and MP3 support](https://www.processing.org/reference/libraries/sound/SoundFile.html), while JSyn's [SampleLoader](http://www.softsynth.com/jsyn/docs/javadocs/com/jsyn/util/SampleLoader.html) itself only implements WAV and AIF files. There are a number of different ways to add MP3 support:

The SampleLoader can be set to [use the Java Sound API](http://www.softsynth.com/jsyn/docs/javadocs/com/jsyn/util/SampleLoader.html#setJavaSoundPreferred-boolean-) for audio file parsing instead of JSyn's own implementation. Two downsides/obstacles: firstly, Java Sound is not available at all under Android; secondly, MP3 parsing is not supported out of the box, but would need to be added through a [Java Service Provider Plugin](http://www.javazoom.net/mp3spi/mp3spi.html) (3 small jars to be shipped with the library). This is what Minim does, but note that despite the supposedly clean API this route still requires [some extra treatment of MP3 samples](https://github.com/ddf/Minim/blob/f1e7d55ee34d237e118c562ee4e90348c5d7e5c0/src/main/java/ddf/minim/javasound/JSMinim.java#L279).

Getting this route to work with JSyn has not been fruitful so far. Calling `SampleLoader.loadFloatSample()` on an MP3 `File` expectedly produces a

```
java.io.IOException: Unsupported audio file type.
	at com.jsyn.util.soundfile.CustomSampleLoader.loadFloatSample(Unknown Source)
```
Setting `SampleLoader.setJavaSoundPreferred(true)` first but without the SPI plugin gives rise to a

```
javax.sound.sampled.UnsupportedAudioFileException: Stream of unsupported format
	at java.desktop/javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1020)
```
After adding `mp3spi1.9.5.jar`, `tritonus_share.jar` and `jl1.0.1.jar` to the classpath (like Minim), it instead becomes a

```
java.lang.NullPointerException
	at com.jsyn.data.FloatSample.<init>(Unknown Source)
	at com.jsyn.util.JavaSoundSampleLoader.loadFloatSample(Unknown Source)
	at com.jsyn.util.JavaSoundSampleLoader.loadFloatSample(Unknown Source)
	at com.jsyn.util.SampleLoader.loadFloatSample(Unknown Source)
```
i.e. the Java Sound `AudioInputStream` can be instantiated, but for some reason not read by JSyn (the exception thrown is intentionally uninformative, see the [release notes for JSyn V16.5.6](http://www.softsynth.com/jsyn/docs/release16.php). I still need to dig into the source of the problem based on the JSyn code).

Another frequently reported workaround that might fix the issue is to [explicitly decode the MP3 file to a PCM sample in memory](http://www.javazoom.net/mp3spi/documents.html). Using the same approach, i.e.

```
AudioInputStream a = AudioSystem.getAudioInputStream(new File("test.mp3"));
if (a.getFormat() instanceof MpegAudioFormat) {
	AudioFormat decodedFormat = new AudioFormat(AudioFormat.Encoding.PCM_SIGNED,
			a.getFormat().getSampleRate(),
			16,
			a.getFormat().getChannels(),
			a.getFormat().getChannels() * 2,
			a.getFormat().getSampleRate(),
			false);
	AudioInputStream dec = AudioSystem.getAudioInputStream(decodedFormat, a);
	SampleLoader.loadFloatSample(dec);
}
```
in turn triggers a

```
java.io.IOException: mark not supported
	at org.tritonus.share.sampled.convert.TAsynchronousFilteredAudioInputStream.reset(TAsynchronousFilteredAudioInputStream.java:245)
	at java.desktop/com.sun.media.sound.SunFileReader.getAudioFileFormat(SunFileReader.java:59)
	at java.desktop/com.sun.media.sound.WaveExtensibleFileReader.getAudioInputStream(WaveExtensibleFileReader.java:259)
	at java.desktop/javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1016)
	at com.jsyn.util.JavaSoundSampleLoader.loadFloatSample(Unknown Source)
	at com.jsyn.util.SampleLoader.loadFloatSample(Unknown Source)
```

**Comment by kevinstadler** [comment]
This is working for now using the [JavaMP3 library](https://github.com/delthas/JavaMP3) including [fixes from my own fork](https://github.com/kevinstadler/JavaMP3/commits/master). It still requires testing on Android, plus the overhead of decoding the entire mp3 upon instantiation of the SoundFile might not make for a great user experience and should maybe be moved to its own thread.

**Comment by gohai** [comment]
I just tried the `Test` example on top of the latest commit: on the Raspberry Pi 3+, decoding the 0:13 `test.mp3` takes a staggering 69 seconds 🚨Java is maxing out one core, memory consumption looks reasonably while it runs. Curious what makes this so inefficient..

**Comment by gohai** [comment]
https://github.com/jnorthr/FreeMP3 ?
